#
# Конфигурационный файл WorldGuard
#
# О редактировании этого файла:
# - НЕ ИСПОЛЬЗУЙТЕ ТАБУЛЯЦИЮ (TABS). Вы ДОЛЖНЫ использовать пробелы, иначе Bukkit
#   выдаст ошибку. Если вы используете редактор вроде Notepad++ (рекомендуется для 
#   пользователей Windows), настройте его на «замену табуляции пробелами». 
#   В Notepad++ это можно изменить в: Опции > Настройки > Автозамена (или Меню языков).
# - Не удаляйте отступы. Они нужны для того, чтобы параметры находились в своих
#   категориях (например, «enforce-single-session» находится в категории «protection»).
# - Если вы хотите проверить формат этого файла перед тем, как загрузить его 
#   в WorldGuard, вставьте его содержимое на http://yaml-online-parser.appspot.com/
#   и проверьте, не выдаст ли он «ERROR:».
# - Строки, начинающиеся с символа #, являются комментариями и игнорируются.
#
# ВНИМАНИЕ:
# Не забудьте проверить таблицу совместимости WorldGuard, чтобы узнать,
# не работают ли какие-либо функции некорректно в вашей версии Bukkit.
#

# -- Это значение должно автоматически заменяться плагином в игре --