#
# Конфигурационный файл WorldGuard.
#
# Это файл конфигурации для конкретного мира. Он влияет только на один
# соответствующий мир.
#
# О редактировании этого файла:
# - НЕ ИСПОЛЬЗУЙТЕ ТАБУЛЯЦИЮ. Вы ДОЛЖНЫ использовать пробелы, иначе Bukkit
#   выдаст ошибку. Если вы используете редактор вроде Notepad++ (рекомендуется
#   для пользователей Windows), вы должны настроить его на «замену табуляции пробелами».
#   В Notepad++ это можно изменить в: Настройки > Опции > Языки.
# - Не удаляйте отступы. Они сделаны для того, чтобы некоторые записи находились
#   в категориях (например, «enforce-single-session» находится в категории «protection»).
# - Если вы хотите проверить формат этого файла перед тем, как добавить его
#   в WorldGuard, вставьте его содержимое на http://yaml-online-parser.appspot.com/
#   и проверьте, не выдаст ли он «ERROR:».
# - Строки, начинающиеся с символа #, являются комментариями и игнорируются.
#

# -- Это значение должно быть автоматически заменено плагином в игре --